# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-13 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hero', '0006_auto_20170813_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ongoing', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('date_started', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hero.Group')),
            ],
        ),
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added')),
                ('name', models.CharField(max_length=200)),
                ('date', models.IntegerField(verbose_name='in game date')),
                ('entry', models.TextField(verbose_name='entry')),
                ('adventure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adventure.Adventure')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hero.Hero')),
            ],
        ),
    ]
