# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-20 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0008_auto_20170820_1254'),
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NSC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NSCGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.AlterModelOptions(
            name='diaryentry',
            options={'ordering': ('adventure', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='adventure',
            unique_together=set([('group', 'name')]),
        ),
        migrations.AddField(
            model_name='nscgroup',
            name='adventure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure.Adventure'),
        ),
        migrations.AddField(
            model_name='nsc',
            name='groups',
            field=models.ManyToManyField(to='adventure.NSCGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='nscgroup',
            unique_together=set([('adventure', 'name')]),
        ),
    ]
