# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-05 10:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ongoing', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('date_started', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added')),
                ('name', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200, verbose_name='in game date')),
                ('order', models.IntegerField()),
                ('entry', models.TextField(verbose_name='entry')),
                ('adventure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hero.Adventure')),
            ],
            options={
                'ordering': ('adventure', 'order'),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('rule_version', models.CharField(choices=[('DSA4', 'Das Schwarze Auge, v4.1'), ('SPLITTERMOND', 'Splittermond'), ('GENERAL', 'Generic setting')], default='DEFAULT', max_length=20)),
                ('description', models.CharField(max_length=140)),
                ('game_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gaming_group_master', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(related_name='gaming_group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('char_sheet', models.FileField(blank=True, null=True, upload_to='')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hero.Group')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NSC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NSCGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=7)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hero.Group')),
            ],
        ),
        migrations.AddField(
            model_name='nsc',
            name='groups',
            field=models.ManyToManyField(to='hero.NSCGroup'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hero.Hero'),
        ),
        migrations.AddField(
            model_name='adventure',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hero.Group'),
        ),
        migrations.AlterUniqueTogether(
            name='nscgroup',
            unique_together=set([('group', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='hero',
            unique_together=set([('group', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='diaryentry',
            unique_together=set([('adventure', 'order')]),
        ),
        migrations.AlterUniqueTogether(
            name='adventure',
            unique_together=set([('group', 'name')]),
        ),
    ]
