# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-15 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hero.Player')),
            ],
        ),
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateTimeField(verbose_name='date added')),
                ('name', models.CharField(max_length=200)),
                ('date', models.IntegerField(verbose_name='in game date')),
                ('entry', models.TextField(verbose_name='Eintrag')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hero.Diary')),
            ],
        ),
    ]
