# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 16:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hero', '0002_diary_diaryentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='game_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gaming_group_master', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='players',
            field=models.ManyToManyField(related_name='gaming_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hero',
            name='char_sheet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hero.Hero'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='date_registered',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
