# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-13 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0005_auto_20170809_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='diary',
        ),
        migrations.DeleteModel(
            name='Diary',
        ),
        migrations.DeleteModel(
            name='DiaryEntry',
        ),
    ]
