# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-13 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0006_auto_20170813_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='char_sheet',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
