# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-20 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0007_auto_20170813_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='hero',
            unique_together=set([('group', 'name')]),
        ),
    ]
